export const mockUser = {
  id: "user_1",
  email: "john@example.com",
  name: "John Doe",
  isPro: true,
};

export const mockItemTypes = [
  { id: "type_snippet", name: "Snippet", icon: "<>", color: "#a78bfa", isSystem: true },
  { id: "type_prompt", name: "Prompt", icon: "✦", color: "#60a5fa", isSystem: true },
  { id: "type_command", name: "Command", icon: ">_", color: "#34d399", isSystem: true },
  { id: "type_note", name: "Note", icon: "📄", color: "#fbbf24", isSystem: true },
  { id: "type_file", name: "File", icon: "📎", color: "#f472b6", isSystem: true },
  { id: "type_image", name: "Image", icon: "🖼️", color: "#fb923c", isSystem: true },
  { id: "type_url", name: "URL", icon: "🔗", color: "#94a3b8", isSystem: true },
];

export const mockCollections = [
  {
    id: "col_1",
    name: "React Patterns",
    description: "Common React patterns and hooks",
    isFavorite: true,
    itemCount: 12,
    userId: "user_1",
  },
  {
    id: "col_2",
    name: "Python Snippets",
    description: "Useful Python code snippets",
    isFavorite: false,
    itemCount: 8,
    userId: "user_1",
  },
  {
    id: "col_3",
    name: "Context Files",
    description: "AI context files for projects",
    isFavorite: true,
    itemCount: 5,
    userId: "user_1",
  },
  {
    id: "col_4",
    name: "Interview Prep",
    description: "Technical interview preparation",
    isFavorite: false,
    itemCount: 24,
    userId: "user_1",
  },
  {
    id: "col_5",
    name: "Git Commands",
    description: "Frequently used git commands",
    isFavorite: true,
    itemCount: 15,
    userId: "user_1",
  },
  {
    id: "col_6",
    name: "AI Prompts",
    description: "Curated AI prompts for coding",
    isFavorite: false,
    itemCount: 18,
    userId: "user_1",
  },
];

export const mockItemTypeCounts: Record<string, number> = {
  type_snippet: 24,
  type_prompt: 18,
  type_command: 15,
  type_note: 12,
  type_file: 5,
  type_image: 5,
  type_url: 8,
};

export const mockItems = [
  {
    id: "item_1",
    title: "useAuth Hook",
    description: "Custom authentication hook for React applications",
    contentType: "text",
    content: `import { useSession } from 'next-auth/react';\n\nexport function useAuth() {\n  const { data: session, status } = useSession();\n  return { user: session?.user, isLoading: status === 'loading' };\n}`,
    language: "typescript",
    isFavorite: false,
    isPinned: true,
    typeId: "type_snippet",
    collectionId: "col_1",
    userId: "user_1",
    tags: ["react", "auth", "hooks"],
    createdAt: "2025-01-15",
  },
  {
    id: "item_2",
    title: "API Error Handling Pattern",
    description: "Fetch wrapper with exponential backoff retry logic",
    contentType: "text",
    content: `async function fetchWithRetry(url: string, retries = 3) {\n  for (let i = 0; i < retries; i++) {\n    try {\n      return await fetch(url);\n    } catch (e) {\n      if (i === retries - 1) throw e;\n      await new Promise(r => setTimeout(r, 2 ** i * 1000));\n    }\n  }\n}`,
    language: "typescript",
    isFavorite: true,
    isPinned: true,
    typeId: "type_snippet",
    collectionId: "col_1",
    userId: "user_1",
    tags: ["api", "error-handling", "fetch"],
    createdAt: "2025-01-13",
  },
  {
    id: "item_3",
    title: "Git Stash All Changes",
    description: "Stash including untracked files",
    contentType: "text",
    content: "git stash push -u -m 'WIP: feature description'",
    language: null,
    isFavorite: false,
    isPinned: false,
    typeId: "type_command",
    collectionId: "col_5",
    userId: "user_1",
    tags: ["git", "stash"],
    createdAt: "2025-01-10",
  },
  {
    id: "item_4",
    title: "Explain this code",
    description: "Prompt for getting clear code explanations",
    contentType: "text",
    content: "Explain the following code in simple terms. Break it down step by step, mention any patterns used, and flag any potential issues:\n\n[CODE]",
    language: null,
    isFavorite: true,
    isPinned: false,
    typeId: "type_prompt",
    collectionId: "col_6",
    userId: "user_1",
    tags: ["ai", "explain", "code-review"],
    createdAt: "2025-01-08",
  },
  {
    id: "item_5",
    title: "Next.js Project Context",
    description: "AI context file for this Next.js project",
    contentType: "text",
    content: "# Project Context\n\nThis is a Next.js 15 app using TypeScript, Tailwind CSS, and Prisma with PostgreSQL.",
    language: null,
    isFavorite: false,
    isPinned: false,
    typeId: "type_file",
    collectionId: "col_3",
    userId: "user_1",
    tags: ["context", "nextjs"],
    createdAt: "2025-01-05",
  },
];
